### PR TITLE
renamed files

### PR DESCRIPTION
**Pull request by makunomark**
This fixes the renaming of files. Somehow git doesnt see change from `FooBar` to `fooBar` as a change. So I changed the filenames to `foo-bar` case (spinal-case). Then had to refresh the git cache.

### CODE REVIEW

**Comment by makunomark** [comment]
It seemed cleaner, most npm modules also used the case.

**Comment by axpence** [comment]
Is there a react style guide somewhere?
https://github.com/airbnb/javascript/tree/master/react

I really like picking a style guide and sticking to it. Airbnb has the de-facto style guide for Javascript. I'd trust their React style guide. 
https://github.com/airbnb/javascript

**Comment by makunomark** [comment]
Yeah. I have done a google search and lost have come up. All prefer the
case I had before. :-( and the way I spent time changing the case.

**Comment by axpence** [comment]
It is all in good learning 👍

**Comment by makunomark** [comment]
Should we stick to Airbnb's style for this project?

**Comment by axpence** [comment]
Sure ! If you want to. They have the industry standard style guide.

**Pull request merged**
