### PR TITLE
46 project description disappears on mouse over

### PR DESCRIPTION
**Pull request by makunomark**
Done :-)

### CODE REVIEW

**Comment by axpence** [comment]
There's a green line where the title used to be: https://www.dropbox.com/s/pgdbs77ikzm0ckm/Screenshot%202017-06-01%2013.53.59.png?dl=0

**Comment by makunomark** [comment]
Yeah I can see it. I'll fix it.

**Comment by makunomark** [comment]
fixed

**Comment by makunomark** [comment]
We can close this, the changes were merged to `fullpage` branch

**Pull request merged**
